services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recommendations
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: password

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  fastapi:
    build: .
    container_name: recommendation_service
    restart: always
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:password@postgres:5432/recommendations
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  recommendation_worker:
    build: .
    command: ["python", "workers/recommendation_updater.py"]
    depends_on:
      - kafka
      - postgres

  model_trainer:
    build: .
    container_name: model_trainer
    restart: always
    depends_on:
      - clickhouse
      - minio
    command: ["python", "workers/scheduler.py"]

  analytics_worker:
    build: .
    container_name: analytics_worker
    restart: always
    depends_on:
      - clickhouse
    command: ["python", "workers/analytics_processor.py"]


volumes:
  postgres_data:
  clickhouse_data:
  minio_data:
