services:
  # ---- api для mongo пользвательских закладок, лайков/дизлайков, рецензий  ----
  ugc_service:
    build: ./mongo_app/app
    expose:
      - "8766"
    ports:  
      - "8766:8766"        
    # depends_on:
      # - auth
      # - logstash
      # - kibana
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:5044
    #     tag: ugc_service

  # filebeat:
  #     image: elastic/filebeat:8.10.2
  #     volumes:
  #       - /tmp/logs/nginx:/var/log/nginx:ro
  #       - ./infra/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     command: filebeat -e -strict.perms=false
  #     depends_on:
  #       - ugc_service
  #       - nginx
  #       - logstash
  #       - elastic-logs
  #       - kibana
  #     links:
  #       - logstash

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:5044
    #     tag: mongodb_container
    # depends_on:
    #   - logstash
    #   - kibana
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  # # ELK
  # logstash:
  #   image: logstash:8.10.2
  #   environment:
  #     XPACK_MONITORING_ENABLED: "false"
  #     ES_HOST: "elastic-logs:9200"
  #   ports:
  #     - "5044:5044/udp"
  #   expose:
  #     - "5044/udp"
  #   volumes:
  #     - ./infra/logstash.conf:/config/logstash.conf:ro
  #   command: logstash -f /config/logstash.conf
  #   depends_on:
  #     - elastic-logs

  # kibana:
  #   image: kibana:8.10.2
  #   ports:
  #     - "5602:5602"
  #   depends_on:
  #     - logstash
  #     - elastic-logs
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elastic-logs:9200

  # elastic-logs:
  #   image: elasticsearch:8.10.2
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - ingest.geoip.downloader.enabled=false
  #     - ES_JAVA_OPTS=-Xms3g -Xmx3g
  #   ports:
  #     - "9200:9200"
  #   expose:
  #     - "9200"
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5
  #   volumes:
  #     - ./infra/esdata:/usr/share/elasticsearch/data

  nginx:
    image: nginx:latest
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./infra/nginx/logs/:/var/log/nginx/
    depends_on:
      - ugc_service
    ports:
    - "80:80"
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://127.0.0.1:5044
    #     tag: nginx

volumes:
  mongodb_data: