services:
  # ---- api для mongo пользвательских закладок, лайков/дизлайков, рецензий  ----
  ugc_service:
    build: ./mongo_app/app
    expose:
      - "8766"
    ports:  
      - "8766:8766"        

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
  #     - ./infra/nginx/logs/:/var/log/nginx/
  #   depends_on:
  #     - ugc_service
  #   ports:
  #   - "80:80"

volumes:
  mongodb_data: