global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['recommend:8001']  # Метрики FastAPI
  - job_name: 'metrics'
    static_configs:
      - targets: ['metrics:8002']  # Метрики Precision/Recall